### ISSUE TITLE
Shorter Teasers please

### ISSUE THREAD

**Issue by jauggy** [beyond-all-reason/spads_config_bar#142]
Sample teaser: `Boss name | Custom Battle 8 vs 8` should become simply `8 vs 8`. It's taking up too much space on lobby browser and other info is getting cut off.

Discord discussion
https://discord.com/channels/549281623154229250/549281623577722899/1269025159558332599

**Comment by FIr3baL** [comment]
> Based on the discord discussion: https://discord.com/channels/549281623154229250/549281623577722899/1269025159558332599
> 
> Many people just want `8v8` and nothing else. We don't need `Team` or `Custom Battle`. For the boss name it can take up a lot of space, but maybe that is something Chobby can handle for people with small screens i.e. me.
> 
> @FIr3baL any reason why we can't show symbols in the lobby title? I know that σ symbol for sigma works in other areas for Chobby.

Since chobby is written in LUA, it should be complete compatible with UTF-8. 
I guess it's a transport problem. 
You could try changing c.battle.update_lobby_title and s.battle.update_lobby_title to use base64 encoded strings to bypass any problems, that can occur with UTF-8. Unfortunatly this would need to be changed in teiserver+barmanager+chobby.

**Comment by jauggy** [comment]
Yeah probably not worth it if we have to do that. But thanks.

**Comment by MitjaGrabbe** [comment]
Hello, as Jauggy mentioned me as a frequent lobby hoster would prefer 8v8 without a boss name or custom game or teamgame prefix. People are mostly interested in the min rating or min chev level which is currently for most players not visible. 

I host lobbies often and I have to say that this is one of the changes I do really dislike. to be precise I just stopped hosting lobbies as it is way to hard to create lobby names that read pleasant for the eye, hence people join. of course glitter lobbies etc dont face that issue. 

Even if it isnt a custom game and so a proper ranked and the boss name then is shown in the back, it is still spam. Talked to many players. We seems to agree that this change isnt perceived as good. I rather would welcome a popup if I hover over a lobby with my mouse, or completly new collums in the lobby list seperated as maps currently are shown.

**Comment by jauggy** [comment]
Near and Kyouma and also agreed that boss is not necessary in the title https://discord.com/channels/549281623154229250/549281623577722899/1269025823395024988

Choice is also not a fan of the current naming scheme:
https://discord.com/channels/549281623154229250/549281623577722899/1269055882797518939

**Comment by jauggy** [comment]
@DeviousNull sounds good

**Comment by jauggy** [comment]
OK I see some good improvements in production now. Closing.
