### ISSUE TITLE
ClusterManager: Random crashes on preset clusters/instances

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spads_config_bar#30]
<details>
<pre>
20220111084848 - INFO     - [SPADS] File "/opt/spads/var/ClusterManager/[teh]host25team[0]/mapHashes.dat" dumped
20220111084848 - INFO     - [SPADS] File "/opt/spads/var/ClusterManager/[teh]host25team[0]/userData.dat" dumped
20220111094547 - NOTICE   - [SPADS] <BarManager> LEFTBATTLE['LEFTBATTLE', '11', '[teh]Beherith']
20220111094849 - INFO     - [SPADS] File "/opt/spads/var/ClusterManager/[teh]host25team[0]/mapHashes.dat" dumped
20220111094849 - INFO     - [SPADS] File "/opt/spads/var/ClusterManager/[teh]host25team[0]/userData.dat" dumped
20220111104149 - NOTICE   - [SPADS] <BarManager> LEFTBATTLE['LEFTBATTLE', '11', 'AKU']
20220111104850 - INFO     - [SPADS] File "/opt/spads/var/ClusterManager/[teh]host25team[0]/mapHashes.dat" dumped
20220111104850 - INFO     - [SPADS] File "/opt/spads/var/ClusterManager/[teh]host25team[0]/userData.dat" dumped
20220111114851 - INFO     - [SPADS] File "/opt/spads/var/ClusterManager/[teh]host25team[0]/mapHashes.dat" dumped
20220111114851 - INFO     - [SPADS] File "/opt/spads/var/ClusterManager/[teh]host25team[0]/userData.dat" dumped
20220111124559 - NOTICE   - [SPADS] Spring archives have been modified 40 seconds ago, auto-reloading archives...
20220111124715 - ERROR    - [SimpleEvent] Error in forked call, Magic number checking on storable string failed at /usr/lib/x86_64-linux-gnu/perl/5.30/Storable.pm line 471, at /opt/spads/SimpleEvent.pm line 424.
20220111124715 - WARNING  - [SPADS] Spring archives loading process took 1 minute and 16 seconds
20220111124715 - ERROR    - [SPADS] Failed to load archives, undefined mods data (unitsync library crash ?)
20220111124715 - NOTICE   - [SPADS] AutoHost shutdown scheduled (reason: Unable to auto-reload Spring archives)
20220111124715 - NOTICE   - [SPADS] Game is not running, exiting
20220111124715 - NOTICE   - [SimpleEvent] Stopping event loop...
20220111124715 - NOTICE   - [SimpleEvent] Event loop stopped
20220111124715 - NOTICE   - [SPADS] <BarManager> Plugin unloaded
20220111124715 - NOTICE   - [SPADS] <InGameMute> Plugin unloaded
20220111124715 - NOTICE   - [SPADS] <JsonStatus> Plugin unloaded
20220111124715 - NOTICE   - [SPADS] <ClusterManager> Plugin unloaded [exiting]
20220111124715 - NOTICE   - [SPADS] <AutoRegister> Plugin unloaded
20220111124715 - NOTICE   - [SpringLobbyInterface] Disconnecting from server2.beyondallreason.info:8200
20220111124715 - NOTICE   - [SpringAutoHostInterface] Closing AutoHost interface
20220111124715 - INFO     - [SPADS] File "/opt/spads/var/ClusterManager/[teh]host25team[0]/mapHashes.dat" dumped
20220111124716 - INFO     - [SPADS] File "/opt/spads/var/ClusterManager/[teh]host25team[0]/userData.dat" dumped
</pre>
<details>

**Comment by Yaribz** [comment]
`Error in forked call`
`Failed to load archives, undefined mods data (unitsync library crash ?)`

As discussed previously, this is due to the unitsync library crashing, probably due to another concurrent process updating the archives at the same time.

**Comment by badosu** [comment]
I'm using sequential unitsync load, this is the errored unitsync load log: 
<details>
<pre>
[t=00:00:00.000025] [DataDirLocater::FindWriteableDataDir] using writeable data-directory "/opt/spads/var/ClusterManager/[teh]host25team[0]/"
[t=00:00:00.000026] Using writeable configuration source: "/opt/spads/var/ClusterManager/[teh]host25team[0]/springsettings.cfg"
[t=00:00:00.000028] Using additional read-only configuration source: "/spring-engines/spring_bar_.BAR105.105.1.1-739-ga241485_linux-64-minimal-portable/springsettings.cfg"
[t=00:00:00.000030] LogOutput initialized. Logging to /opt/spads/var/ClusterManager/[teh]host25team[0]/unitsync.log
[t=00:00:00.021032] [DataDirLocater::FindWriteableDataDir] using writeable data-directory "/opt/spads/var/ClusterManager/[teh]host25team[0]/"
[t=00:00:00.021803] [DataDirLocater::Check] Portable Mode!
[t=00:00:00.021812] [DataDirLocater::FilterUsableDataDirs] using read-write data directory: /opt/spads/var/ClusterManager/[teh]host25team[0]/
[t=00:00:00.021820] [DataDirLocater::FilterUsableDataDirs] using read-only data directory: /spring-engines/spring_bar_.BAR105.105.1.1-739-ga241485_linux-64-minimal-portable/
[t=00:00:00.021832] [DataDirLocater::FilterUsableDataDirs] using read-only data directory: /spring-data/
[t=00:00:00.162784] Scanning: /spring-data/maps
[t=00:00:00.304574] Scanning: /spring-data/packages
[t=00:00:00.395329] Scanning: /spring-engines/spring_bar_.BAR105.105.1.1-739-ga241485_linux-64-minimal-portable/base
[t=00:00:00.401725] Scanning: /spring-engines/spring_bar_.BAR105.105.1.1-739-ga241485_linux-64-minimal-portable/maps
[t=00:00:00.404657] Scanning: /spring-engines/spring_bar_.BAR105.105.1.1-739-ga241485_linux-64-minimal-portable/games
[t=00:00:00.460900] [unitsync] [UnitSync::Init] initialized 105.1.1-739-ga241485 BAR105 (Headless Unitsync) (call 0)
[t=00:00:25.720928] [unitsync] Error: GetMapChecksum: std::bad_alloc
</pre>
</details>

**Comment by Yaribz** [comment]
> I'm using sequential unitsync load

Yes I know, this means the other process shouldn't be a SPADS instance, but something else updating the archives.
pr-downloader or things like that, as we already discussed.

> Error: GetMapChecksum: std::bad_alloc

This is the error making the unitsync library crash I guess. Maybe you are just missing some memory ?

**Comment by badosu** [comment]
Hmm, I see
