### ISSUE TITLE
Block add/clearboxes command when voting to start a game

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spads_config_bar#34]
e.g.

```
[addBox]
::voting|100:
battle,pv:player,spec:stopped|10:10
::|100:
```

Context: https://discordapp.com/channels/549281623154229250/855772061095559179/919144547907403776

See https://github.com/beyond-all-reason/spads_config_bar/commit/8cfe284080f9543e343e10de9d46cf334ffd00df for an example of a commit changing command ACL

**Comment by Beherith** [comment]
Fixed
